[package]
name = "compio-py"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MulanPSL-2.0"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
pyo3 = { version = "0.27.1", features = ["extension-module"] }
once_cell = "1.21.3"
scoped-tls = "1.0.1"
async-task = { version = "4.7.1", default-features = false }
either = "1.15.0"

[dependencies.compio]
git = "https://github.com/compio-rs/compio.git"
rev = "5e8326fed91973c1fb5aa404b689c46d1d6501c4"
default-features = false
features = ["io-uring", "polling"]
